### ISSUE TITLE
Using registry certs require docker daemon restart

### ISSUE THREAD

**Issue by lcarva** [lcarva/osbs-box#11]
When osbs-box starts it generates the identity certificate used by the registry container. Because this is a self-signed cert, it requires making it available at `/etc/docker/certs.d/172.17.0.1:5000/ca.crt`.
The problem with this approach is that docker daemon will only read this certificate during start up time, requiring docker daemon to be restarted. Obviously, this kills the osbs-box containers in the process. This also crashed my system (fedora 25) :(

Two possible solutions:
1) Instruct users to add the IP range of docker0 interface to their list of insecure registries: `172.17.0.0/16`. This is system dependent unfortunately.
2) Require that certs be created before hand, and provide a script to facilitate that.

**Comment by lcarva** [comment]
@vrutkovs what do you think?

**Comment by vrutkovs** [comment]
Yes, we'll have to go with option 2 I guess

**Comment by vrutkovs** [comment]
Hmm, weird, I tested this and docker restart was not required in `docker-1.13.1-19.git27e468e.fc26.x86_64`. Maybe instead the upgrade should be recommended?

**Comment by lcarva** [comment]
huh interesting. I'm fine as is then.
