### ISSUE TITLE
Remove dnf/yum update from Dockerfiles

### ISSUE THREAD

**Issue by lcarva** [lcarva/osbs-box#21]
We should remove any sort of `dnf/yum update` from the Dockerfiles. One of the concerns is that parent images don't get updated fast enough, leaving stale packages in images. However, doing a yum update for every container slows down significantly creating a new instance of osbs-box.

**Comment by vrutkovs** [comment]
I guess its a good idea to have and option set for this - e.g. `UPDATES` build arg
