### ISSUE TITLE
Create a single base image for all services

### ISSUE THREAD

**Issue by vrutkovs** [lcarva/osbs-box#25]
This would be much easier to update and construct, after PR for multiple distributions is merged

**Comment by lcarva** [comment]
If we have a single base image, doesn't that affect how multiple distributions is approached?

**Comment by vrutkovs** [comment]
It would, so before starting a work on this I'd rather have multiple distributions PR merged first.

I'm thinking it would be like this:
 * Distribution specific Dockerfiles for service would start with `FROM osbs-box-base:<distroname>`
 * Common parts of distro-specific base images would be moved to distro-specific base image
 * Distro-specific base image would be built first, it would accept `UPDATES` and optionally `UPDATES_TESTING` build arguments

I think this should make osbs-box startup faster

**Comment by lcarva** [comment]
Let's be very careful about the "common parts" that go into the base image. I'm thinking it should be minimal. Perhaps just handling `UPDATES`, `UPDATES_TESTING`, and installing custom yum repository.

**Comment by vrutkovs** [comment]
Yep, all `yum/dnf installs` probably shouldn't go in
